spring:
  application:
    name: global-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/prasune/food-dlivery-app/git-local-config
          clone-on-start: true
server:
  port: 8888