spring:
  application:
    name: global-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/prasune/spring-cloud-config-git-repo
          clone-on-start: true
server:
  port: 8888